Application Directory Structure
yugandhargangu/Bettle-Track pull request #11
Opened 2017-02-17 10:42 UTC by yugandhargangu

1. Bettle track application directory structure.
2. Power point file of directory
3. Gradle script files and sub modules.
4. Spring boot application configuration

2017-02-18 01:10 UTC, shashankitmaster requested changes

2017-02-18 01:10 UTC, shashankitmaster commented on .travis.yml
> +  - oraclejdk8
Please use openjdk for java instead of oracle.

2017-02-18 01:10 UTC, shashankitmaster commented on application/bettle/.project
> +<?xml version="1.0" encoding="UTF-8"?>
Remove this file and above `.classpath` . add `.gitignore` file

2017-02-18 01:10 UTC, shashankitmaster commented on application/bettle/bettle-entity/build.gradle
> +apply plugin: "java"
@ranjeet1515 : Add lombok plugin and reduce the code of setter and getter to annotation. 

Refer: https://projectlombok.org/mavenrepo/

2017-02-18 01:10 UTC, shashankitmaster commented on application/bettle/bettle-jpa/src/main/java/com/bettle/track/jpa/repos/BaseRepository.java
> +    @Query("UPDATE #{#entityName} e SET e.active_flag = 0 WHERE e.id = :id")
Can we move queries to resources folder and make use of annotation with fetches the query from classpath.

2017-02-18 01:11 UTC, shashankitmaster commented
Change destination branch to `release` branch

2017-02-18 06:59 UTC, yugandhargangu commented on .travis.yml
> +  - oraclejdk8
travis-ci doesn't have openjdk8.
https://github.com/travis-ci/travis-ci/issues/6483

2017-02-19 04:33 UTC, yugandhargangu commented on application/bettle/bettle-jpa/src/main/java/com/bettle/track/jpa/repos/BaseRepository.java
> +    @Query("UPDATE #{#entityName} e SET e.active_flag = 0 WHERE e.id = :id")
Yes. This part will be done in jpa specific branch but not in this branch. So I removed this class.

2017-02-19 04:46 UTC, yugandhargangu commented on application/bettle/.project
> +<?xml version="1.0" encoding="UTF-8"?>
Done.

2017-02-19 04:47 UTC, yugandhargangu commented on application/bettle/bettle-entity/build.gradle
> +apply plugin: "java"
Done

2017-02-21 00:15 UTC, shashankitmaster commented on .travis.yml
> +  - oraclejdk8
I got your point but I think Oracle will soon licence JDK use.

2017-02-21 00:21 UTC, shashankitmaster requested changes

2017-02-21 00:21 UTC, shashankitmaster commented on application/bettle/bettle-common/src/main/java/com/bettle/track/enums/CustomFieldType.java
> +    public int getId() {
@yugandhargangu : Please get rid of getter and setter as we using lombok plugin for that.
 
Please try to do that for all classes

2017-02-21 00:21 UTC, shashankitmaster commented on application/bettle/bettle-jpa/src/main/java/com/bettle/track/jpa/repos/BaseRepository.java
> +    @Query("UPDATE #{#entityName} e SET e.active_flag = 0 WHERE e.id = :id")
@yugandhargangu : Got it

2017-02-24 12:52 UTC, yugandhargangu commented
Updated with bettle-repo and bettle-service modules.

2017-02-26 11:22 UTC, shashankitmaster approved these changes
Please merge ur branch

2017-02-26 11:22 UTC, shashankitmaster commented on application/bettle/bettle-common/src/main/java/com/bettle/track/enums/CustomFieldType.java
> +    public int getId() {
Okay. I am sorry I thought those are classes. I am approving.

2017-02-26 11:23 UTC, merged