Feature/application entity
yugandhargangu/Bettle-Track pull request #12
Opened 2017-02-26 04:02 UTC by ranjeet1515

Added database entities.

2017-02-26 11:24 UTC, shashankitmaster requested changes
Please remove .keep files from repos.

2017-02-26 11:24 UTC, shashankitmaster commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/common/AppSettings.java~
> +package com.bettle.track.entities.common;
Please remove this class

2017-02-26 11:24 UTC, shashankitmaster commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/issue/Issue.java~
> +package com.bettle.track.entities.issue;
Please remove this class

2017-02-26 11:29 UTC, shashankitmaster requested changes

2017-02-26 11:29 UTC, shashankitmaster commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/user/User.java
> +    public Set<Dashboard> getListDashboards() {
Remove this getter & setter  if you are using `@Data` in your class.

2017-02-26 11:47 UTC, yugandhargangu commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/issue/Category.java
> +public class Category extends AbstractParentEntity {
Add @FilterDefs for active categories.

2017-02-26 11:47 UTC, yugandhargangu commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/issue/Issue.java
> +        @FilterDef(name = "issue", defaultCondition = "active_flag = 1")
Change @FilterDef name from "issue" to "active_issues"

2017-02-26 11:49 UTC, yugandhargangu commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/issue/IssueAttchment.java
> +        @FilterDef(name = "issue_attachment", defaultCondition = "active_flag = 1")
Change @FilterDef name from "issue_attachment" to "active_issue_attachments".

2017-02-26 11:50 UTC, yugandhargangu commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/issue/IssueCategory.java
> +        @FilterDef(name = "issues_categories", defaultCondition = "active_flag = 1")
Change @FilterDef name from "issues_categories" to "active_issues_categories".

2017-02-26 11:51 UTC, yugandhargangu commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/issue/IssueComment.java
> +        @FilterDef(name = "issue_comments", defaultCondition = "active_flag = 1")
Change @FilterDef from "issue_comments" to "active_issue_comments".

2017-02-26 11:52 UTC, yugandhargangu commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/issue/IssueDesc.java
> +        @FilterDef(name = "issue_desc", defaultCondition = "active_flag = 1")
Change @FIlterDef name from "issue_desc" to "active_issue_desc"

2017-02-26 11:52 UTC, yugandhargangu commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/issue/IssueField.java
> +        @FilterDef(name = "issue_field", defaultCondition = "active_flag = 1")
Change @FilterDef name from "issue_field" to "active_issue_fields".

2017-02-26 11:53 UTC, yugandhargangu commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/issue/IssueFilter.java
> +        @FilterDef(name = "Issue_filter", defaultCondition = "active_flag = 1")
Change @FilterDef name from "Issue_filter" to "active_issue_filters".

2017-02-26 11:54 UTC, yugandhargangu commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/issue/IssueFilterField.java
> +        @FilterDef(name = "Issue_filter_field", defaultCondition = "active_flag = 1")
Change @FilterDef name from "Issue_filter_field" to "active_issue_filter_fields".

2017-02-26 11:56 UTC, yugandhargangu commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/issue/IssueFilterSharing.java
> +        @FilterDef(name = "Issue_filter_sharing", defaultCondition = "active_flag = 1")
Change @FilterDef name from "Issue_filter_sharing" to "active_issue_filter_sharing".

2017-02-26 11:57 UTC, yugandhargangu commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/issue/IssueHistory.java
> +        @FilterDef(name = "issue_history", defaultCondition = "active_flag = 1")
Change @FilterDef name from "issue_history" to "active_issue_history".

2017-02-26 11:59 UTC, yugandhargangu commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/issue/IssueProcedure.java
> +        @FilterDef(name = "issue_procedures", defaultCondition = "active_flag = 1")
Change @FilterDef name from "issue_procedures" to "active_issue_procedures".

2017-02-26 12:00 UTC, yugandhargangu commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/issue/Tag.java
> +public class Tag extends AbstractParentEntity {
Add @FilterDefs to find active tag records.

2017-02-26 12:01 UTC, yugandhargangu commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/project/Project.java
> +public class Project extends AbstractParentEntity {
Add @FilterDefs to find active projects.

2017-02-26 12:05 UTC, yugandhargangu commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/user/User.java
> +public class User extends AbstractParentEntity {
Add @FilterDefs for active users.

2017-02-26 12:06 UTC, yugandhargangu commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/user/UserGroup.java
> +public class UserGroup extends AbstractParentEntity {
Add @FilterDefs for active user groups.

2017-02-26 12:07 UTC, yugandhargangu commented on application/bettle/bettle-entity/src/main/java/com/bettle/track/entities/user/UserInfo.java
> +@FilterDef(name = "active_user_info", defaultCondition = "active_flag = 1")
Add @FilterDefs and keep @FilterDef in @FilterDefs as array.
Add @Where above @FilterDefs annotation.

2017-02-27 00:46 UTC, shashankitmaster commented
@ranjeet1515 : Please add package-info.java file for your package.

2017-02-27 13:18 UTC, ranjeet1515 commented
Done with all changes.

2017-02-28 00:31 UTC, shashankitmaster approved these changes

2017-03-10 04:10 UTC, shashankitmaster requested changes
Please change all `application.properties` to `application.yml`

2017-03-10 04:19 UTC, shashankitmaster submitted a review, later dismissed
Add `sourceSet` to `build.gradle`

```java
sourceSets {
    main {
        java {
            srcDirs = ['src/java']
        }
        resources {
            srcDirs = ['src/resources']
        }
    }
}
```

2017-04-30 08:11 UTC, yugandhargangu commented
Reviewed 21 of 54 files at r2, 40 of 40 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 20 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/yugandhargangu/bettle-track/12)*
<!-- Sent from Reviewable.io -->

2017-05-01 00:50 UTC, shashankitmaster approved these changes

2017-05-01 00:56 UTC, shashankitmaster commented
Reviewed 21 of 54 files at r2, 40 of 40 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/yugandhargangu/bettle-track/12)*
<!-- Sent from Reviewable.io -->

2017-05-01 01:05 UTC, merged